förtydligar 410 felsidan
riksantikvarieambetet/ksamsok pull request #1
Opened 2020-12-28 18:01 UTC by Abbe98

2020-12-31 13:50 UTC, salgo60 commented
Borde det inte finnas en översättning så vi dödliga förstår var felet är och hur vi felanmäler det hela

* exempel
  * http://kulturarvsdata.se/raa/bbr/21300000018193
    * bbr --> [Bebyggelseregistret](https://www.raa.se/hitta-information/bebyggelseregistret-bebr/) felanmälan görs på xxxx
  * http://kulturarvsdata.se/raa/fmi/10160302490201
    * fmi -->  [Fornsök](https://www.raa.se/hitta-information/fornsok/kontakta-fornsok/) felanmälan görs på yyyy
    
På sikt vore det även bra att se om det redan finns felanmält och att det finns en orsak varför det inte funkar

2021-01-12 23:07 UTC, carwash requested changes
Fixa stavfel; annars bra. :)

2021-01-12 23:07 UTC, carwash commented on src/main/webapp/errors/error410.html
> +                Sidan du sökte efter finns inte längre, det kan vara så att den är borttagen/förändrad hos källan eller har tagitborts för att den inte uppnår K-samsöks kvalitetskrav.</p>
```suggestion
                Sidan du sökte efter finns inte längre, det kan vara så att den är borttagen/förändrad hos källan eller har tagits bort för att den inte uppnår K-samsöks kvalitetskrav.</p>
```

2021-01-13 06:55 UTC, salgo60 commented
"tagit borts för att den inte uppnår K-samsöks kvalitetskrav."

Det där tror jag inte är sant det är massa interna problem inom RAÄ att system inte verkar synkas. Konsekvensen för oss externa är att K-samsök skapar bara massa problem och ger inget mervärde.... om inte K-samsök synkroniseras internt så fyller den ingen uppgift utan det är bättre för oss externa att länka direkt till slutappen i detta fall bebyggelseregistret... 

* kolla [wikipedia Malldiskussion:BBR-länk](https://sv.wikipedia.org/wiki/Malldiskussion:BBR-l%C3%A4nk)
  * [bebyggelseregistret anlaggningId=21300000003117](http://www.bebyggelseregistret.raa.se/bbr2/anlaggning/visaHistorik.raa?page=historik&visaHistorik=true&anlaggningId=21300000003117)  har under Relaterade länkar **http://kulturarvsdata.se/raa/bbr/html/21300000003117**
![image](https://user-images.githubusercontent.com/14206509/104416142-8ff91d80-5573-11eb-9ab5-e7904c50dfd6.png)

![image](https://user-images.githubusercontent.com/14206509/104416182-a2735700-5573-11eb-80ec-85ae3cefc642.png)

dvs. en applikation bebyggelseregistret säger att den URL som skall användas är kulturarvsdata.se länken som inte finns det känns mer som intern oordning än kvalitetskrav mer brist på kvalitet ;-)  

När vi testade de 160 000 kopplingar vi har till RAÖ i WIkidata så var det > 4000 där vi hade problem med BBR se del av [lista](https://gist.github.com/salgo60/4f2fa0370a5541712fd274e5b9e84b26) ([GIST]([url](https://gist.github.com/salgo60/a4ebde4f0a279d5f9479aeaf7b846403)))

2021-01-13 16:27 UTC, Abbe98 commented
@carwash uppdaterat!

2021-01-13 16:56 UTC, merged